### ISSUE TITLE
Missing argparse attribute

### ISSUE THREAD

**Issue by didiemme** [LemonATsu/A-NeRF#1]
Hi, 
i was trying to run your code but it's missing an argparse attribute and i didn't catch from the paper o other places which number to put in.
d.
 
python run_nerf.py --config configs/surreal/surreal.txt --basedir logs  --expname surreal_model
init meta
Traceback (most recent call last):
  File "run_nerf.py", line 627, in <module>
    train()
  File "run_nerf.py", line 498, in train
    train_loader, render_data, data_attrs = load_data(args)
  File "/home/ddimauro/Workspace_Nerf/A-NeRF/core/load_data.py", line 76, in load_data
    N_iter=args.n_iters + 10 + args.pretrain_mapper)
AttributeError: 'Namespace' object has no attribute 'pretrain_mapper'

**Comment by LemonATsu** [comment]
Problem fixed, please `git pull` and let me know if it works.
