### ISSUE TITLE
how to use your model for customized data?

### ISSUE THREAD

**Issue by Holmes-Alan** [LemonATsu/A-NeRF#12]
Good work! I wonder how can I implement it on my own video?

**Comment by LemonATsu** [comment]
Thanks for your interest in our work. Please refer to #5 to see previous discussions regarding using custom dataset.

**Comment by xizero00** [comment]
Hi @LemonATsu 
Thanks for sharing you excellent work!
I run the core/load_h36m.py and find it raised errors
```
FileNotFoundError
[Errno 2] No such file or directory: 'data/h36m/S1_clean_bkgds.npy'
  File "/home/dx/projects/A-NeRF/core/load_h36m.py", line 134, in process_h36m_data
    bkgds = np.load(os.path.join(data_path, f"{subject.replace('s', '')}_clean_bkgds.npy"))
  File "/home/dx/projects/A-NeRF/core/load_h36m.py", line 456, in <module>
    data = process_h36m_data(data_path, subject, camera_name=camera, extend_iter=extend_iter)
```
It seems these missing files are not included in the code.
Could you tell me how to generate these missing files?
Thanks!

**Comment by LemonATsu** [comment]
@xizero00 Sorry for the late reply. I was busy traveling. If you still need the details regarding H3.6M dataset, please send me an e-mail and we can discuss it.
