### ISSUE TITLE
Cannot extract mesh for the learned character nor render mesh as described in README.md

### ISSUE THREAD

**Issue by domattioli** [LemonATsu/A-NeRF#16]
https://github.com/LemonATsu/A-NeRF/blob/fe553717052cc2696714177566641cdaaba0459a/run_render.py#L973

I've successfully ran the first test with run_render.py to render the learned model. However, running the second test (rendering the mesh) produces an error referencing that import line.
`ModuleNotFoundError: No module named 'mcubes'`.

My environment is setup precisely as described in the README.md. I tried manually installing the supposedly missing [package](https://anaconda.org/flyem-forge/marching_cubes) but that results in a python version conflict because A-NeRF requires 3.8:
`Specifications: - marching_cubes -> python[version='>=3.7,<3.8.0a0|>=3.7.6,<3.8.0a0']`

**Comment by LemonATsu** [comment]
Hi @domattioli, you can try building the package directly from the repo: https://github.com/pmneila/PyMCubes and see if that works.
