### ISSUE TITLE
Cannot change subject in config file.

### ISSUE THREAD

**Issue by domattioli** [LemonATsu/A-NeRF#17]
https://github.com/LemonATsu/A-NeRF/blob/fe553717052cc2696714177566641cdaaba0459a/configs/surreal/surreal.txt#L7

Changing the subject config value to "male", for example, when running the default Test of run_render for SURREAL yields a KeyError. Shouldn't this input setting be acceptable given that the [dataset](https://github.com/gulvarol/surreal) has two inputs (0: 'female', 1: 'male') for 'Gender'?

**Comment by LemonATsu** [comment]
Hi @domattioli, the male version dataset is not available at the moment. The female dataset should be enough for debugging/quick development purpose.
