### ISSUE TITLE
Novel Poses

### ISSUE THREAD

**Issue by mgholamikn** [LemonATsu/A-NeRF#18]
Thank you so much for sharing the code. Could you please let me know how I could feed random novel poses to the trained model and render novel poses?

**Comment by LemonATsu** [comment]
Hi @mgholamikn, sorry for the late reply. You can take a look at how we did the retargeting here: https://github.com/LemonATsu/A-NeRF/blob/main/run_render.py#L179

Let me know if you have any questions!

**Comment by mgholamikn** [comment]
Thank you so much for your reply!

**Comment by domattioli** [comment]
Is it correct that the current A-NeRF version cannot accept input information from a .fbx file from Mixamo, for example, to render novel poses for the default Surreal character? I haven't been able to figure this out.
