### ISSUE TITLE
Query on skeleton projection from 3dto2d

### ISSUE THREAD

**Issue by Dipankar1997161** [LemonATsu/A-NeRF#25]
hello @LemonATsu,

I was wondering what is this following "c2ws" in case of converting skeleton 3d to 2d, is it a 4x4 nerf extrinsic matrix or is it the Batch_rays origin and direction which are usually present in NeRFs.
https://github.com/LemonATsu/A-NeRF/blob/b1a4698e54d5fd294b2953346863619bb902554c/core/utils/skeleton_utils.py#L442

Because, I want to project the 3d skeletons on the 2d images but for custom images, so it would be great to know about it.
If you can inform me that, it would be really wonderful for me.

**Comment by LemonATsu** [comment]
@Dipankar1997161 Sorry for the late reply. The `c2ws` here is the camera-to-world matrix (camera pose), and is supposed to be the inverse of camera extrinsics.

However, we follow the original NeRF implementation to use OpenGL camera coordinates (y, z axes are flipped) for model training, so we need to do one extra flip to turn the camera back to OpenCV for 3d-to-2d projection.
