### ISSUE TITLE
Could you release the prepocess code for custom dataset?

### ISSUE THREAD

**Issue by tlok666** [LemonATsu/A-NeRF#5]
Hi,

Thanks for sharing this interesting work. In the code of 'core/load_XXX.py', the loaded dataset '*.h5' has already been preprocessed. Could you release the preprocess code for the custom dataset？

**Comment by LemonATsu** [comment]
Hi @tlok666 , we have provided the reference code/function `process_[dataset_name].py` for how we process the data in each of the `load_[dataset_name].py` data.

**Comment by xizero00** [comment]
Hi,
Thanks for sharing your excellent work!
When I execute the core/load_h36m.py
https://github.com/LemonATsu/A-NeRF/blob/main/core/load_h36m.py#L134
I find it raised error as follows:
```
FileNotFoundError
[Errno 2] No such file or directory: 'data/h36m/S1_clean_bkgds.npy'
  File "/home/dx/projects/A-NeRF/core/load_h36m.py", line 134, in process_h36m_data
    bkgds = np.load(os.path.join(data_path, f"{subject.replace('s', '')}_clean_bkgds.npy"))
  File "/home/dx/projects/A-NeRF/core/load_h36m.py", line 453, in <module>
    data = process_h36m_data(data_path, subject, camera_name=camera, extend_iter=extend_iter)
```
Could you please provide these missing files?
Thanks a lot!
