### ISSUE TITLE
which SMPL model 

### ISSUE THREAD

**Issue by tau-yihouxiang** [LemonATsu/A-NeRF#6]
Thank you for releasing the source code. However, I am confused about the SMPL model. Which SMPL model is used and what is the full name of the SMPL model? What is the folder structure of data/smpl?

**Comment by LemonATsu** [comment]
Hi @tau-yihouxiang, we use the neutral model from SMPL.
The folder structure is as the following
```                                                                                      
├── core
 │   ....
├── smpl
│   ├── mixamo 
│   │   ├── SMPL_NEUTRAL.pkl
│   │   │
│   │   ├── data
│   │   │  ├── J_regressor_h36m.npy # for evaluating in H36M format

```
